"""first version

Revision ID: 84e1a09c28da
Revises: 
Create Date: 2022-07-11 17:53:34.229317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84e1a09c28da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userTable',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.TEXT(), nullable=True),
    sa.Column('firstname', sa.VARCHAR(length=50), nullable=True),
    sa.Column('lastname', sa.VARCHAR(length=50), nullable=True),
    sa.Column('password', sa.TEXT(), nullable=True),
    sa.Column('dob', sa.TEXT(), nullable=True),
    sa.Column('mobileNumber', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='application'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userTable', schema='application')
    # ### end Alembic commands ###
